### ISSUE TITLE
NucPlot.py error

### ISSUE THREAD

**Issue by CEPHAS-01** [mrvollger/NucFreq#5]
Hi,
Many thanks for this tool to evaluate the quality of an assembly.

I was trying to make a plot of a region with NucPlot.py but encountered the following error.

Using a font-size of 16
Packages loaded
Reading in the region or bed argument(s).
Reading in NucFreq from region: h1tg000093l:3555483-3557483
Traceback (most recent call last):
  File "/NucFreq/NucPlot.py", line 178, in <module>
    cov = getCovByBase(contig, start, end)
  File "/NucFreq/NucPlot.py", line 156, in getCovByBase
    contig, start=start, stop=end, read_callback="nofilter", quality_threshold=None
  File "pysam/libcalignmentfile.pyx", line 1592, in pysam.libcalignmentfile.AlignmentFile.count_coverage
TypeError: 'NoneType' object is not subscriptable

my command structure was like thus:

python /NucFreq/NucPlot.py --bed bedFile.bed -t 8 sortedBamFileInput.bam outputFileName

Any suggestions on what to do?

Thanks in advance.

**Comment by CEPHAS-01** [comment]
Hi,
For other folks who may have similar issues, I figured out the problem after some more digging.
Pysam version was the problem. I had to install the latest version and this made the problem go away.
I will close this issue immediately.

Many thanks for the tool.
